package entity;

import java.math.BigDecimal;
import java.util.Date;

public class CouponPacketMetaData {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_packet_meta.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_packet_meta.record_id
     * 记录id
     * @mbggenerated
     */
    private Long recordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_packet_meta.member_id
     *
     * @mbggenerated
     */
    private Long memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_packet_meta.coupon_code
     * 券code
     * @mbggenerated
     */
    private String couponCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_packet_meta.status
     * 使用状态
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_packet_meta.expiration_time
     * 优惠券过期时间
     * @mbggenerated
     */
    private Date expirationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_packet_meta.related_order_id
     * 使用该券的订单id
     * @mbggenerated
     */
    private Long relatedOrderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_packet_meta.amount_saved
     * 已省金额
     * @mbggenerated
     */
    private BigDecimal amountSaved;

    private Long futureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_packet_meta.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_packet_meta.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_packet_meta.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_packet_meta.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_coupon_packet_meta.last_updated_at
     * 最后修改时间
     * @mbggenerated
     */
    private Date lastUpdatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_packet_meta.id
     *
     * @return the value of t_coupon_packet_meta.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_packet_meta.id
     *
     * @param id the value for t_coupon_packet_meta.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_packet_meta.record_id
     *
     * @return the value of t_coupon_packet_meta.record_id
     *
     * @mbggenerated
     */
    public Long getRecordId() {
        return recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_packet_meta.record_id
     *
     * @param recordId the value for t_coupon_packet_meta.record_id
     *
     * @mbggenerated
     */
    public void setRecordId(Long recordId) {
        this.recordId = recordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_packet_meta.member_id
     *
     * @return the value of t_coupon_packet_meta.member_id
     *
     * @mbggenerated
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_packet_meta.member_id
     *
     * @param memberId the value for t_coupon_packet_meta.member_id
     *
     * @mbggenerated
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_packet_meta.coupon_code
     *
     * @return the value of t_coupon_packet_meta.coupon_code
     *
     * @mbggenerated
     */
    public String getCouponCode() {
        return couponCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_packet_meta.coupon_code
     *
     * @param couponCode the value for t_coupon_packet_meta.coupon_code
     *
     * @mbggenerated
     */
    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode == null ? null : couponCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_packet_meta.status
     *
     * @return the value of t_coupon_packet_meta.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_packet_meta.status
     *
     * @param status the value for t_coupon_packet_meta.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_packet_meta.expiration_time
     *
     * @return the value of t_coupon_packet_meta.expiration_time
     *
     * @mbggenerated
     */
    public Date getExpirationTime() {
        return expirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_packet_meta.expiration_time
     *
     * @param expirationTime the value for t_coupon_packet_meta.expiration_time
     *
     * @mbggenerated
     */
    public void setExpirationTime(Date expirationTime) {
        this.expirationTime = expirationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_packet_meta.related_order_id
     *
     * @return the value of t_coupon_packet_meta.related_order_id
     *
     * @mbggenerated
     */
    public Long getRelatedOrderId() {
        return relatedOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_packet_meta.related_order_id
     *
     * @param relatedOrderId the value for t_coupon_packet_meta.related_order_id
     *
     * @mbggenerated
     */
    public void setRelatedOrderId(Long relatedOrderId) {
        this.relatedOrderId = relatedOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_packet_meta.amount_saved
     *
     * @return the value of t_coupon_packet_meta.amount_saved
     *
     * @mbggenerated
     */
    public BigDecimal getAmountSaved() {
        return amountSaved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_packet_meta.amount_saved
     *
     * @param amountSaved the value for t_coupon_packet_meta.amount_saved
     *
     * @mbggenerated
     */
    public void setAmountSaved(BigDecimal amountSaved) {
        this.amountSaved = amountSaved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_packet_meta.created_at
     *
     * @return the value of t_coupon_packet_meta.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_packet_meta.created_at
     *
     * @param createdAt the value for t_coupon_packet_meta.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_packet_meta.created_by
     *
     * @return the value of t_coupon_packet_meta.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_packet_meta.created_by
     *
     * @param createdBy the value for t_coupon_packet_meta.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy == null ? null : createdBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_packet_meta.updated_at
     *
     * @return the value of t_coupon_packet_meta.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_packet_meta.updated_at
     *
     * @param updatedAt the value for t_coupon_packet_meta.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_packet_meta.updated_by
     *
     * @return the value of t_coupon_packet_meta.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_packet_meta.updated_by
     *
     * @param updatedBy the value for t_coupon_packet_meta.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy == null ? null : updatedBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_coupon_packet_meta.last_updated_at
     *
     * @return the value of t_coupon_packet_meta.last_updated_at
     *
     * @mbggenerated
     */
    public Date getLastUpdatedAt() {
        return lastUpdatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_coupon_packet_meta.last_updated_at
     *
     * @param lastUpdatedAt the value for t_coupon_packet_meta.last_updated_at
     *
     * @mbggenerated
     */
    public void setLastUpdatedAt(Date lastUpdatedAt) {
        this.lastUpdatedAt = lastUpdatedAt;
    }

    public Long getFutureId() {
        return futureId;
    }

    public void setFutureId(Long futureId) {
        this.futureId = futureId;
    }
}